package zone.clanker.gradle.generators

import java.io.File

/**
 * Generates root agent instructions files (CLAUDE.md, copilot-instructions.md, etc.)
 * that teach agents about OPSX tasks.
 *
 * For agents that use AGENTS.md (Codex, OpenCode, Crush), the content is appended
 * between markers so user content is preserved.
 */
object InstructionsGenerator {

    private const val MARKER_START = "<!-- OPSX:BEGIN - Generated by openspec-gradle. Do not edit between markers. -->"
    private const val MARKER_END = "<!-- OPSX:END -->"

    private val template: String by lazy {
        val stream = this::class.java.classLoader.getResourceAsStream("templates/instructions.md")
            ?: error("Missing resource: templates/instructions.md — plugin JAR may be corrupted")
        stream.bufferedReader().readText()
    }

    fun generate(
        buildDir: File,
        tools: List<String>
    ): List<GeneratedFile> {
        val generated = mutableListOf<GeneratedFile>()
        val seenPaths = mutableSetOf<String>()

        for (toolId in tools) {
            val adapter = ToolAdapterRegistry.get(toolId) ?: continue
            val relativePath = adapter.getInstructionsFilePath()

            // Deduplicate — multiple agents may share the same path (e.g. AGENTS.md)
            if (relativePath in seenPaths) continue
            seenPaths.add(relativePath)

            val file = File(buildDir, relativePath)
            file.parentFile.mkdirs()

            if (adapter.appendInstructions) {
                // Wrap content in markers for append mode
                file.writeText("$MARKER_START\n\n$template\n$MARKER_END\n")
            } else {
                file.writeText(template)
            }
            generated.add(GeneratedFile(relativePath, file))
        }
        return generated
    }

    /**
     * Install an instructions file, handling append mode.
     * For append-mode files, replaces the marker section or appends if no markers exist.
     * For non-append files, simply overwrites.
     */
    fun install(generated: GeneratedFile, projectDir: File, adapter: ToolAdapter) {
        val target = File(projectDir, generated.relativePath)

        if (!adapter.appendInstructions) {
            // Simple overwrite
            target.parentFile.mkdirs()
            generated.file.copyTo(target, overwrite = true)
            return
        }

        // Append mode: preserve user content, replace OPSX section
        val newContent = generated.file.readText()

        if (!target.exists()) {
            target.parentFile.mkdirs()
            target.writeText(newContent)
            return
        }

        val existing = target.readText()
        val startIdx = existing.indexOf(MARKER_START)
        val endIdx = existing.indexOf(MARKER_END)

        if (startIdx >= 0 && endIdx >= 0 && startIdx < endIdx) {
            // Replace existing OPSX section
            val before = existing.substring(0, startIdx)
            val after = existing.substring(endIdx + MARKER_END.length)
            target.writeText(before + newContent + after)
        } else {
            // No existing markers — append
            target.writeText(existing.trimEnd() + "\n\n" + newContent)
        }
    }

    /**
     * Remove OPSX section from an append-mode instructions file.
     * Returns true if a file was actually modified or deleted.
     */
    fun clean(projectDir: File, adapter: ToolAdapter): Boolean {
        val target = File(projectDir, adapter.getInstructionsFilePath())
        if (!target.exists()) return false

        if (!adapter.appendInstructions) {
            target.delete()
            return true
        }

        val content = target.readText()
        val startIdx = content.indexOf(MARKER_START)
        val endIdx = content.indexOf(MARKER_END)

        if (startIdx >= 0 && endIdx >= 0 && startIdx < endIdx) {
            val before = content.substring(0, startIdx)
            val after = content.substring(endIdx + MARKER_END.length)
            val cleaned = (before + after).trim()
            if (cleaned.isEmpty()) {
                target.delete()
            } else {
                target.writeText(cleaned + "\n")
            }
            return true
        }
        return false
    }
}
