package zone.clanker.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.artifacts.ProjectDependency
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.plugins.JavaPluginExtension
import org.gradle.api.tasks.*
import java.io.File

@CacheableTask
abstract class OpenSpecContextTask : DefaultTask() {

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val buildFiles: ConfigurableFileCollection

    @get:OutputFile
    abstract val contextFile: RegularFileProperty

    init {
        group = "openspec"
        description = "Generates .openspec/context.md with project metadata, dependencies, module graph, and architecture hints extracted from Gradle."
    }

    @TaskAction
    fun generate() {
        val out = contextFile.get().asFile
        out.parentFile.mkdirs()

        val sb = StringBuilder()
        val root = project.rootProject

        sb.appendLine("# Project Context (auto-generated by openspec-gradle)")
        sb.appendLine()
        sb.appendLine("## Overview")
        sb.appendLine("- **Name:** ${root.name}")
        if (root.group.toString().isNotBlank()) sb.appendLine("- **Group:** ${root.group}")
        if (root.version.toString() != "unspecified" && root.version.toString().isNotBlank())
            sb.appendLine("- **Version:** ${root.version}")
        sb.appendLine("- **Gradle version:** ${project.gradle.gradleVersion}")
        sb.appendLine("- **Build file:** ${root.buildFile.name}")

        // Language/JVM info
        appendLanguageInfo(sb, root)

        // Multi-project module graph
        val subprojects = root.subprojects
        if (subprojects.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## Modules")
            sb.appendLine()
            for (sub in subprojects.sortedBy { it.path }) {
                sb.appendLine("### ${sub.path}")
                sb.appendLine("- **Directory:** ${sub.projectDir.relativeTo(root.projectDir)}")
                val projectDeps = mutableListOf<String>()
                sub.configurations.forEach { config ->
                    config.dependencies.filterIsInstance<ProjectDependency>().forEach { dep ->
                        // dep.name is the project name (last segment of path)
                        // For multi-project, find matching subproject
                        val matchingProject = root.subprojects.find { it.name == dep.name }
                        if (matchingProject != null) {
                            projectDeps.add(matchingProject.path)
                        } else {
                            projectDeps.add(":${dep.name}")
                        }
                    }
                }
                if (projectDeps.isNotEmpty()) {
                    sb.appendLine("- **Module dependencies:** ${projectDeps.distinct().sorted().joinToString(", ")}")
                }
                sb.appendLine()
            }
        }

        // Applied plugins & framework detection
        val allPlugins = mutableSetOf<String>()
        val frameworks = mutableListOf<String>()
        val errors = mutableListOf<String>()

        collectPlugins(root, allPlugins, frameworks)
        subprojects.forEach { collectPlugins(it, allPlugins, frameworks) }

        sb.appendLine("## Applied Plugins")
        sb.appendLine()
        for (p in allPlugins.sorted()) {
            sb.appendLine("- $p")
        }

        if (frameworks.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## Frameworks Detected")
            sb.appendLine()
            for (f in frameworks.distinct().sorted()) {
                sb.appendLine("- $f")
            }
        }

        // Architecture hints
        val hints = generateHints(frameworks.distinct())
        if (hints.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## Architecture Hints")
            sb.appendLine()
            for (h in hints) {
                sb.appendLine("- $h")
            }
        }

        // Source sets
        appendSourceSets(sb, root, root)
        subprojects.sortedBy { it.path }.forEach { appendSourceSets(sb, it, root) }

        // Dependencies
        appendDependencies(sb, root, errors)
        subprojects.sortedBy { it.path }.forEach { appendDependencies(sb, it, errors) }

        // Errors
        if (errors.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## Errors & Warnings")
            sb.appendLine()
            for (e in errors) {
                sb.appendLine("- $e")
            }
        }

        out.writeText(sb.toString())
        logger.lifecycle("OpenSpec: Generated context at ${out.relativeTo(root.projectDir)}")
    }

    private fun appendLanguageInfo(sb: StringBuilder, project: org.gradle.api.Project) {
        try {
            val javaExt = project.extensions.findByType(JavaPluginExtension::class.java)
            if (javaExt != null) {
                val sourceCompat = javaExt.sourceCompatibility
                sb.appendLine("- **Java compatibility:** $sourceCompat")
            }
        } catch (_: Exception) {}

        // Kotlin version from plugin
        try {
            val kotlinVersion = project.buildscript.configurations
                .flatMap { it.dependencies }
                .find { it.group == "org.jetbrains.kotlin" && it.name.startsWith("kotlin-gradle-plugin") }
                ?.version
            if (kotlinVersion != null) {
                sb.appendLine("- **Kotlin:** $kotlinVersion")
            }
        } catch (_: Exception) {}
    }

    private fun appendSourceSets(sb: StringBuilder, proj: org.gradle.api.Project, root: org.gradle.api.Project) {
        try {
            val javaExt = proj.extensions.findByType(JavaPluginExtension::class.java) ?: return
            val sourceSets = javaExt.sourceSets
            val label = if (proj == root && root.subprojects.isEmpty()) "Source Sets" else "Source Sets (${proj.path})"
            val entries = mutableListOf<String>()
            sourceSets.forEach { ss ->
                val dirs = ss.allSource.srcDirs.filter { it.exists() }
                if (dirs.isNotEmpty()) {
                    entries.add("- **${ss.name}:** ${dirs.joinToString(", ") { it.relativeTo(root.projectDir).path }}")
                }
            }
            if (entries.isNotEmpty()) {
                sb.appendLine()
                sb.appendLine("## $label")
                sb.appendLine()
                entries.forEach { sb.appendLine(it) }
            }
        } catch (_: Exception) {}
    }

    private fun appendDependencies(sb: StringBuilder, proj: org.gradle.api.Project, errors: MutableList<String>) {
        val interestingConfigs = setOf("implementation", "api", "compileOnly", "runtimeOnly",
            "testImplementation", "testCompileOnly", "testRuntimeOnly")
        val label = if (proj == proj.rootProject && proj.rootProject.subprojects.isEmpty()) "Dependencies" else "Dependencies (${proj.path})"
        val entries = mutableListOf<String>()

        for (configName in interestingConfigs) {
            val config = try { proj.configurations.findByName(configName) } catch (_: Exception) { null }
            if (config == null) continue
            val deps = config.dependencies.filter { it !is ProjectDependency }
            if (deps.isEmpty()) continue
            for (dep in deps) {
                entries.add("- `$configName`: ${dep.group ?: ""}:${dep.name}:${dep.version ?: ""}")
            }
        }

        if (entries.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## $label")
            sb.appendLine()
            entries.forEach { sb.appendLine(it) }
        }
    }

    private val FRAMEWORK_MAP = mapOf(
        "org.springframework.boot" to "Spring Boot",
        "org.jetbrains.kotlin.jvm" to "Kotlin (JVM)",
        "org.jetbrains.kotlin.android" to "Kotlin (Android)",
        "com.android.application" to "Android Application",
        "com.android.library" to "Android Library",
        "org.jetbrains.compose" to "Compose Desktop",
        "io.ktor" to "Ktor",
        "com.google.protobuf" to "Protobuf/gRPC",
        "org.jetbrains.kotlin.plugin.serialization" to "Kotlin Serialization",
        "org.flywaydb.flyway" to "Flyway",
        "org.liquibase.gradle" to "Liquibase",
    )

    private fun collectPlugins(proj: org.gradle.api.Project, plugins: MutableSet<String>, frameworks: MutableList<String>) {
        proj.plugins.forEach { plugin ->
            val id = plugin.javaClass.name
            plugins.add(id)
        }
        // Check by known IDs
        for ((pluginId, frameworkName) in FRAMEWORK_MAP) {
            if (proj.plugins.hasPlugin(pluginId)) {
                frameworks.add(frameworkName)
                plugins.add(pluginId)
            }
        }
        // Also collect from applied plugin container with IDs
        try {
            proj.pluginManager.let { pm ->
                for ((pluginId, _) in FRAMEWORK_MAP) {
                    if (pm.hasPlugin(pluginId)) {
                        plugins.add(pluginId)
                    }
                }
            }
        } catch (_: Exception) {}
    }

    private fun generateHints(frameworks: List<String>): List<String> {
        val hints = mutableListOf<String>()
        if ("Spring Boot" in frameworks) {
            hints.add("Spring Boot → likely controller/service/repository pattern")
            if ("Flyway" in frameworks || "Liquibase" in frameworks) {
                hints.add("Spring Boot + database migrations → schema changes need migration files")
            }
        }
        if (frameworks.any { it.startsWith("Android") }) {
            hints.add("Android → activities/fragments, manifest, resource-based UI or Compose")
        }
        if ("Compose Desktop" in frameworks) {
            hints.add("Compose Desktop → declarative UI with composable functions")
        }
        if ("Ktor" in frameworks) {
            hints.add("Ktor → routing DSL, application modules pattern")
        }
        if ("Protobuf/gRPC" in frameworks) {
            hints.add("Protobuf/gRPC → .proto definitions generate code, don't edit generated sources")
        }
        if ("Kotlin Serialization" in frameworks) {
            hints.add("Kotlin Serialization → uses @Serializable, not Jackson/Gson")
        }
        return hints
    }
}
