package zone.clanker.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.*

@UntrackedTask(because = "Reads dynamic task graph at execution time")
abstract class OpenSpecDevloopTask : DefaultTask() {

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    init {
        group = "opsx"
        description = "[tool] Dev commands reference. " +
            "Output: .opsx/devloop.md. " +
            "Use when: You need build/test/run commands for each module. " +
            "Chain: Use after opsx-modules to understand what to build."
    }

    @TaskAction
    fun generate() {
        val out = outputFile.get().asFile
        out.parentFile.mkdirs()

        val sb = StringBuilder()
        sb.appendLine("# Dev Commands (auto-generated by openspec-gradle)")
        sb.appendLine()

        val root = project.rootProject
        val projects = if (root.subprojects.isNotEmpty()) {
            listOf(root) + root.subprojects.sortedBy { it.path }
        } else {
            listOf(root)
        }

        for (proj in projects) {
            appendDevCommands(sb, proj, root)
        }

        out.writeText(sb.toString())
        logger.lifecycle("OpenSpec: Generated devloop at ${out.relativeTo(root.projectDir)}")
    }

    private fun appendDevCommands(sb: StringBuilder, proj: org.gradle.api.Project, root: org.gradle.api.Project) {
        val taskNames = proj.tasks.names
        val label = if (proj == root && root.subprojects.isEmpty()) "Root" else proj.path
        val prefix = when {
            proj == root -> ""
            else -> "${proj.path}:"
        }

        sb.appendLine("## $label")
        sb.appendLine()

        // Build commands
        val buildTasks = listOf("build", "assemble", "classes", "jar").filter { it in taskNames }
        if (buildTasks.isNotEmpty()) {
            sb.appendLine("### Build")
            sb.appendLine()
            for (t in buildTasks) {
                sb.appendLine("```bash")
                sb.appendLine("./gradlew $prefix$t")
                sb.appendLine("```")
            }
            sb.appendLine()
        }

        // Test commands
        val testTasks = listOf("test", "check").filter { it in taskNames }
        if (testTasks.isNotEmpty()) {
            sb.appendLine("### Test")
            sb.appendLine()
            for (t in testTasks) {
                sb.appendLine("```bash")
                sb.appendLine("./gradlew $prefix$t")
                sb.appendLine("```")
            }
            sb.appendLine()
        }

        // Run commands
        val runTasks = listOf("run", "bootRun").filter { it in taskNames }
        if (runTasks.isNotEmpty()) {
            sb.appendLine("### Run")
            sb.appendLine()
            for (t in runTasks) {
                sb.appendLine("```bash")
                sb.appendLine("./gradlew $prefix$t")
                sb.appendLine("```")
            }
            sb.appendLine()
        }

        // Lint/format
        val lintTasks = listOf("ktlintCheck", "ktlintFormat", "detekt", "spotlessCheck", "spotlessApply", "lint")
            .filter { it in taskNames }
        if (lintTasks.isNotEmpty()) {
            sb.appendLine("### Lint / Format")
            sb.appendLine()
            for (t in lintTasks) {
                sb.appendLine("```bash")
                sb.appendLine("./gradlew $prefix$t")
                sb.appendLine("```")
            }
            sb.appendLine()
        }
    }
}
