package zone.clanker.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.artifacts.ProjectDependency
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.*

@UntrackedTask(because = "Dependency resolution is inherently dynamic and not cacheable")
abstract class OpenSpecDepsTask : DefaultTask() {

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    init {
        group = "opsx"
        description = "[tool] Dependency resolver. " +
            "Output: .opsx/deps.md. " +
            "Use when: You need full dependency list with GAV coordinates, classified as local vs external. " +
            "Chain: Use with opsx-modules for dependency graph."
    }

    @TaskAction
    fun generate() {
        val out = outputFile.get().asFile
        out.parentFile.mkdirs()

        val sb = StringBuilder()
        sb.appendLine("# Dependencies (auto-generated by openspec-gradle)")
        sb.appendLine()

        val root = project.rootProject
        val projects = if (root.subprojects.isNotEmpty()) {
            listOf(root) + root.subprojects.sortedBy { it.path }
        } else {
            listOf(root)
        }

        for (proj in projects) {
            appendProjectDeps(sb, proj, root)
        }

        out.writeText(sb.toString())
        logger.lifecycle("OpenSpec: Generated deps at ${out.relativeTo(root.projectDir)}")
    }

    private fun appendProjectDeps(sb: StringBuilder, proj: org.gradle.api.Project, root: org.gradle.api.Project) {
        val interestingConfigs = setOf(
            "implementation", "api", "compileOnly", "runtimeOnly",
            "testImplementation", "testCompileOnly", "testRuntimeOnly"
        )

        val moduleDeps = mutableListOf<String>()
        val externalDeps = mutableListOf<String>()

        // Try resolving versions from classpaths
        val isOffline = proj.gradle.startParameter.isOffline
        val resolvedVersions = mutableMapOf<String, String>()
        if (isOffline) {
            logger.warn("OpenSpec: Offline mode — skipping dependency resolution for ${proj.path}")
        } else {
            for (configName in listOf("compileClasspath", "runtimeClasspath", "testCompileClasspath")) {
                val config = try { proj.configurations.findByName(configName) } catch (_: Exception) { null }
                if (config == null || !config.isCanBeResolved) continue
                try {
                    config.resolvedConfiguration.firstLevelModuleDependencies.forEach { dep ->
                        resolvedVersions["${dep.moduleGroup}:${dep.moduleName}"] = dep.moduleVersion
                    }
                } catch (e: Exception) {
                    logger.warn("OpenSpec: Failed to resolve $configName for ${proj.path}: ${e.message}")
                }
            }
        }

        for (configName in interestingConfigs) {
            val config = try { proj.configurations.findByName(configName) } catch (_: Exception) { null }
            if (config == null) continue
            for (dep in config.dependencies) {
                if (dep is ProjectDependency) {
                    val depPath = dep.path
                    moduleDeps.add("- `$configName`: $depPath")
                } else {
                    val group = dep.group ?: ""
                    val name = dep.name
                    val version = resolvedVersions["$group:$name"] ?: dep.version ?: ""
                    externalDeps.add("- `$configName`: $group:$name:$version")
                }
            }
        }

        if (moduleDeps.isEmpty() && externalDeps.isEmpty()) return

        val label = if (proj == root && root.subprojects.isEmpty()) "Root" else proj.path
        sb.appendLine("## $label")
        sb.appendLine()

        if (moduleDeps.isNotEmpty()) {
            sb.appendLine("### Local Module Dependencies")
            sb.appendLine()
            moduleDeps.forEach { sb.appendLine(it) }
            sb.appendLine()
        }

        if (externalDeps.isNotEmpty()) {
            sb.appendLine("### External Dependencies")
            sb.appendLine()
            externalDeps.forEach { sb.appendLine(it) }
            sb.appendLine()
        }
    }
}
