package zone.clanker.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.plugins.JavaPluginExtension
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*
import java.io.File

@UntrackedTask(because = "Source directories are determined dynamically at execution time")
abstract class OpenSpecTreeTask : DefaultTask() {

    @get:Input
    @get:Optional
    abstract val module: Property<String>

    @get:Input
    @get:Optional
    abstract val scope: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    init {
        group = "opsx"
        description = "[tool] Source tree generator. " +
            "Output: .openspec/tree.md. " +
            "Options: -Pmodule=name -Pscope=main|test. " +
            "Use when: You need to see the file/directory structure of source sets. " +
            "Chain: Use with opsx-context for full project understanding."
    }

    @TaskAction
    fun generate() {
        val out = outputFile.get().asFile
        out.parentFile.mkdirs()

        val sb = StringBuilder()
        sb.appendLine("# Source Tree (auto-generated by openspec-gradle)")
        sb.appendLine()

        val root = project.rootProject
        val projects = if (module.isPresent) {
            val mod = module.get()
            val found = (root.subprojects + root).filter { it.name == mod || it.path == mod || it.path == ":$mod" }
            if (found.isEmpty()) {
                sb.appendLine("> No module found matching `$mod`")
                out.writeText(sb.toString())
                return
            }
            found
        } else if (root.subprojects.isNotEmpty()) {
            listOf(root) + root.subprojects.sortedBy { it.path }
        } else {
            listOf(root)
        }

        val scopeFilter = if (scope.isPresent) scope.get().lowercase() else null

        for (proj in projects) {
            appendProjectTree(sb, proj, root, scopeFilter)
        }

        out.writeText(sb.toString())
        logger.lifecycle("OpenSpec: Generated source tree at ${out.relativeTo(root.projectDir)}")
    }

    private fun appendProjectTree(sb: StringBuilder, proj: org.gradle.api.Project, root: org.gradle.api.Project, scopeFilter: String?) {
        val javaExt = proj.extensions.findByType(JavaPluginExtension::class.java) ?: return

        val label = if (proj == root && root.subprojects.isEmpty()) "Root" else proj.path
        sb.appendLine("## $label")
        sb.appendLine()

        javaExt.sourceSets.forEach { ss ->
            if (scopeFilter != null && ss.name != scopeFilter) return@forEach

            val existingDirs = ss.allSource.srcDirs.filter { it.exists() }
            if (existingDirs.isEmpty()) return@forEach

            sb.appendLine("### ${ss.name}")
            sb.appendLine()
            sb.appendLine("```")
            for (srcDir in existingDirs) {
                val relPath = srcDir.relativeTo(root.projectDir).path
                val fileCounts = precomputeFileCounts(srcDir)
                val fileCount = fileCounts[srcDir.absolutePath] ?: 0
                sb.appendLine("$relPath/ ($fileCount files)")
                renderDirectoryTree(sb, srcDir, "", fileCounts)
            }
            sb.appendLine("```")
            sb.appendLine()
        }
    }

    private fun precomputeFileCounts(root: File): Map<String, Int> {
        val counts = mutableMapOf<String, Int>()
        root.walkBottomUp().forEach { file ->
            if (file.isFile) {
                // Increment count for every ancestor directory up to root
                var parent = file.parentFile
                while (parent != null && parent.absolutePath.startsWith(root.absolutePath)) {
                    counts[parent.absolutePath] = (counts[parent.absolutePath] ?: 0) + 1
                    if (parent.absolutePath == root.absolutePath) break
                    parent = parent.parentFile
                }
            }
        }
        return counts
    }

    private fun renderDirectoryTree(sb: StringBuilder, dir: File, prefix: String, fileCounts: Map<String, Int>) {
        val children = dir.listFiles()?.sorted() ?: return
        val dirs = children.filter { it.isDirectory }
        val files = children.filter { it.isFile }
        val allItems = dirs + files

        for ((i, item) in allItems.withIndex()) {
            val isLast = i == allItems.size - 1
            val connector = if (isLast) "└── " else "├── "
            val childPrefix = prefix + if (isLast) "    " else "│   "

            if (item.isDirectory) {
                val count = fileCounts[item.absolutePath] ?: 0
                sb.appendLine("$prefix$connector${item.name}/ ($count files)")
                renderDirectoryTree(sb, item, childPrefix, fileCounts)
            } else {
                sb.appendLine("$prefix$connector${item.name}")
            }
        }
    }
}
