package zone.clanker.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.artifacts.ProjectDependency
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.*

@UntrackedTask(because = "Reads dynamic project configurations at execution time")
abstract class OpenSpecModulesTask : DefaultTask() {

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    init {
        group = "opsx"
        description = "[tool] Module graph generator. " +
            "Output: .openspec/modules.md. " +
            "Use when: You need to understand multi-project structure and inter-module dependencies. " +
            "Chain: Use with opsx-deps for full dependency details."
    }

    @TaskAction
    fun generate() {
        val out = outputFile.get().asFile
        out.parentFile.mkdirs()

        val sb = StringBuilder()
        sb.appendLine("# Module Graph (auto-generated by openspec-gradle)")
        sb.appendLine()

        val root = project.rootProject
        val subs = root.subprojects.sortedBy { it.path }

        if (subs.isEmpty()) {
            sb.appendLine("Single-module project: `${root.name}`")
            out.writeText(sb.toString())
            logger.lifecycle("OpenSpec: Generated modules at ${out.relativeTo(root.projectDir)}")
            return
        }

        // Build adjacency: project path -> list of project paths it depends on
        val edges = mutableMapOf<String, MutableList<String>>()
        for (sub in subs) {
            val deps = mutableListOf<String>()
            sub.configurations.forEach { config ->
                config.dependencies.filterIsInstance<ProjectDependency>().forEach { dep ->
                    deps.add(dep.path)
                }
            }
            edges[sub.path] = deps.distinct().sorted().toMutableList()
        }

        // Module list
        sb.appendLine("## Modules (${subs.size})")
        sb.appendLine()
        for (sub in subs) {
            sb.appendLine("- `${sub.path}`")
        }
        sb.appendLine()

        // Dependency graph as ASCII
        sb.appendLine("## Dependency Graph")
        sb.appendLine()
        sb.appendLine("```")
        for (sub in subs) {
            val deps = edges[sub.path] ?: emptyList()
            if (deps.isEmpty()) {
                sb.appendLine("${sub.path}  (no module dependencies)")
            } else {
                sb.appendLine("${sub.path}")
                for ((i, dep) in deps.withIndex()) {
                    val connector = if (i == deps.size - 1) "└── " else "├── "
                    sb.appendLine("  $connector$dep")
                }
            }
        }
        sb.appendLine("```")
        sb.appendLine()

        // Leaf modules (no dependents)
        val allDependedOn = edges.values.flatten().toSet()
        val leaves = subs.filter { it.path !in allDependedOn }.map { it.path }
        if (leaves.isNotEmpty()) {
            sb.appendLine("## Leaf Modules (not depended on by others)")
            sb.appendLine()
            leaves.forEach { sb.appendLine("- `$it`") }
            sb.appendLine()
        }

        // Root modules (no dependencies)
        val roots = subs.filter { (edges[it.path] ?: emptyList()).isEmpty() }.map { it.path }
        if (roots.isNotEmpty()) {
            sb.appendLine("## Root Modules (no module dependencies)")
            sb.appendLine()
            roots.forEach { sb.appendLine("- `$it`") }
            sb.appendLine()
        }

        out.writeText(sb.toString())
        logger.lifecycle("OpenSpec: Generated modules at ${out.relativeTo(root.projectDir)}")
    }
}
