package zone.clanker.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.artifacts.ProjectDependency
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.plugins.JavaPluginExtension
import org.gradle.api.plugins.PluginContainer
import org.gradle.api.tasks.*
import java.io.File

@CacheableTask
abstract class OpenSpecContextTask : DefaultTask() {

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val buildFiles: ConfigurableFileCollection

    @get:OutputFile
    abstract val contextFile: RegularFileProperty

    init {
        group = "openspec"
        description = "Generates .openspec/context.md with project metadata, dependencies, module graph, and architecture hints extracted from Gradle."
    }

    @TaskAction
    fun generate() {
        val out = contextFile.get().asFile
        out.parentFile.mkdirs()

        val sb = StringBuilder()
        val root = project.rootProject

        sb.appendLine("# Project Context (auto-generated by openspec-gradle)")
        sb.appendLine()

        // ── Overview ──
        sb.appendLine("## Overview")
        sb.appendLine("- **Name:** ${root.name}")
        if (root.group.toString().isNotBlank()) sb.appendLine("- **Group:** ${root.group}")
        if (root.version.toString() != "unspecified" && root.version.toString().isNotBlank())
            sb.appendLine("- **Version:** ${root.version}")
        sb.appendLine("- **Gradle:** ${project.gradle.gradleVersion}")
        sb.appendLine("- **Build:** ${root.buildFile.name}")
        appendLanguageInfo(sb, root)

        // ── VCS ──
        appendGitInfo(sb, root.projectDir)

        // ── Modules (multi-project) ──
        val subprojects = root.subprojects
        if (subprojects.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## Modules (${subprojects.size})")
            sb.appendLine()
            for (sub in subprojects.sortedBy { it.path }) {
                sb.appendLine("### ${sub.path}")
                sb.appendLine("- **Path:** ${sub.projectDir.relativeTo(root.projectDir)}/")

                // Applied plugins (just the interesting ones)
                val subPluginIds = resolvePluginIds(sub.plugins)
                val interestingPlugins = subPluginIds.filter { !it.startsWith("org.gradle.") }
                if (interestingPlugins.isNotEmpty()) {
                    sb.appendLine("- **Plugins:** ${interestingPlugins.joinToString(", ")}")
                }

                // Module dependencies
                val projectDeps = mutableListOf<String>()
                sub.configurations.forEach { config ->
                    config.dependencies.filterIsInstance<ProjectDependency>().forEach { dep ->
                        val match = root.subprojects.find { it.name == dep.name }
                        projectDeps.add(match?.path ?: ":${dep.name}")
                    }
                }
                if (projectDeps.isNotEmpty()) {
                    sb.appendLine("- **Depends on:** ${projectDeps.distinct().sorted().joinToString(", ")}")
                }

                // Depended on by
                val dependedOnBy = subprojects.filter { other ->
                    other.configurations.any { config ->
                        config.dependencies.filterIsInstance<ProjectDependency>().any { it.name == sub.name }
                    }
                }.map { it.path }.sorted()
                if (dependedOnBy.isNotEmpty()) {
                    sb.appendLine("- **Depended on by:** ${dependedOnBy.joinToString(", ")}")
                }

                sb.appendLine()
            }
        }

        // ── Included Builds ──
        val includedBuilds = project.gradle.includedBuilds
        if (includedBuilds.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## Included Builds")
            sb.appendLine()
            for (ib in includedBuilds) {
                sb.appendLine("### ${ib.name}")
                sb.appendLine("- **Path:** ${ib.projectDir.relativeTo(root.projectDir)}/")
                appendGitInfo(sb, ib.projectDir, prefix = "  ")
                sb.appendLine()
            }
        }

        // ── Frameworks & Plugins ──
        val allPluginIds = mutableSetOf<String>()
        val frameworks = mutableListOf<String>()
        val allDeps = mutableListOf<String>() // for dep-based framework detection
        val errors = mutableListOf<String>()

        collectPluginsAndFrameworks(root, allPluginIds, frameworks)
        subprojects.forEach { collectPluginsAndFrameworks(it, allPluginIds, frameworks) }

        // Show only non-Gradle plugins
        val userPlugins = allPluginIds.filter { !it.startsWith("org.gradle.") }.sorted()
        if (userPlugins.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## Plugins")
            sb.appendLine()
            for (p in userPlugins) {
                sb.appendLine("- `$p`")
            }
        }

        // ── Dependencies (with resolved versions) ──
        appendDependencies(sb, root, errors, allDeps)
        subprojects.sortedBy { it.path }.forEach { appendDependencies(sb, it, errors, allDeps) }

        // Detect frameworks from dependencies too
        detectFrameworksFromDeps(allDeps, frameworks)

        // ── Frameworks ──
        val distinctFrameworks = frameworks.distinct().sorted()
        if (distinctFrameworks.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## Frameworks Detected")
            sb.appendLine()
            for (f in distinctFrameworks) {
                sb.appendLine("- $f")
            }
        }

        // ── Architecture Hints ──
        val hints = generateHints(distinctFrameworks)
        if (hints.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## Architecture Hints")
            sb.appendLine()
            for (h in hints) {
                sb.appendLine("- $h")
            }
        }

        // ── Source Sets ──
        appendSourceSets(sb, root, root)
        subprojects.sortedBy { it.path }.forEach { appendSourceSets(sb, it, root) }

        // ── Errors ──
        if (errors.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## ⚠️ Errors & Warnings")
            sb.appendLine()
            for (e in errors) {
                sb.appendLine("- $e")
            }
        }

        out.writeText(sb.toString())
        logger.lifecycle("OpenSpec: Generated context at ${out.relativeTo(root.projectDir)}")
    }

    // ── Language Info ──

    private fun appendLanguageInfo(sb: StringBuilder, project: org.gradle.api.Project) {
        try {
            val javaExt = project.extensions.findByType(JavaPluginExtension::class.java)
            if (javaExt != null) {
                sb.appendLine("- **Java:** ${javaExt.sourceCompatibility}")
                try {
                    val toolchain = javaExt.toolchain
                    val langVersion = toolchain.languageVersion.orNull
                    if (langVersion != null) {
                        sb.appendLine("- **Java toolchain:** $langVersion")
                    }
                } catch (_: Exception) {}
            }
        } catch (_: Exception) {}

        // Kotlin version — check for the KotlinPluginVersion class or buildscript deps
        try {
            val kotlinVersion = project.extensions.findByName("kotlin")
                ?.let { it.javaClass.getMethod("getCoreLibrariesVersion").invoke(it) as? String }
            if (kotlinVersion != null) {
                sb.appendLine("- **Kotlin:** $kotlinVersion")
            }
        } catch (_: Exception) {}
    }

    // ── Git Info ──

    private fun appendGitInfo(sb: StringBuilder, projectDir: File, prefix: String = "- ") {
        val gitDir = File(projectDir, ".git")
        if (!gitDir.exists()) return

        try {
            val headFile = File(gitDir, "HEAD")
            if (headFile.exists()) {
                val head = headFile.readText().trim()
                val branch = if (head.startsWith("ref: refs/heads/")) {
                    head.removePrefix("ref: refs/heads/")
                } else {
                    "detached @ ${head.take(8)}"
                }
                sb.appendLine("${prefix}**Branch:** $branch")
            }

            val configFile = File(gitDir, "config")
            if (configFile.exists()) {
                val remoteUrl = parseGitRemoteUrl(configFile)
                if (remoteUrl != null) {
                    sb.appendLine("${prefix}**Remote:** $remoteUrl")
                }
            }
        } catch (_: Exception) {}
    }

    private fun parseGitRemoteUrl(configFile: File): String? {
        var inOrigin = false
        for (line in configFile.readLines()) {
            val trimmed = line.trim()
            if (trimmed == "[remote \"origin\"]") {
                inOrigin = true
            } else if (trimmed.startsWith("[")) {
                inOrigin = false
            } else if (inOrigin && trimmed.startsWith("url = ")) {
                return trimmed.removePrefix("url = ").trim()
            }
        }
        return null
    }

    // ── Plugin Resolution ──

    /** Map of known plugin implementation classes to their plugin IDs */
    private val KNOWN_PLUGIN_IDS = mapOf(
        "org.springframework.boot" to "org.springframework.boot",
        "io.spring.dependency-management" to "io.spring.dependency-management",
        "org.jetbrains.kotlin.jvm" to "org.jetbrains.kotlin.jvm",
        "org.jetbrains.kotlin.android" to "org.jetbrains.kotlin.android",
        "org.jetbrains.kotlin.plugin.serialization" to "org.jetbrains.kotlin.plugin.serialization",
        "org.jetbrains.kotlin.plugin.spring" to "org.jetbrains.kotlin.plugin.spring",
        "org.jetbrains.compose" to "org.jetbrains.compose",
        "com.android.application" to "com.android.application",
        "com.android.library" to "com.android.library",
        "io.ktor" to "io.ktor",
        "com.google.protobuf" to "com.google.protobuf",
        "org.flywaydb.flyway" to "org.flywaydb.flyway",
        "org.liquibase.gradle" to "org.liquibase.gradle",
        "io.gitlab.arturbosch.detekt" to "io.gitlab.arturbosch.detekt",
    )

    private fun resolvePluginIds(plugins: PluginContainer): Set<String> {
        val ids = mutableSetOf<String>()
        plugins.forEach { plugin ->
            val className = plugin.javaClass.name.removeSuffix("_Decorated")
            // Try to map to a nice ID
            val niceId = PLUGIN_CLASS_TO_ID[className]
            if (niceId != null) {
                ids.add(niceId)
            } else {
                // Use the class name but clean it up
                ids.add(className)
            }
        }
        // Also check known plugin IDs directly
        for (pluginId in KNOWN_PLUGIN_IDS.keys) {
            try {
                if (plugins.hasPlugin(pluginId)) {
                    ids.add(pluginId)
                }
            } catch (_: Exception) {}
        }
        return ids
    }

    private val PLUGIN_CLASS_TO_ID = mapOf(
        // Gradle built-in
        "org.gradle.api.plugins.JavaPlugin" to "java",
        "org.gradle.api.plugins.JavaLibraryPlugin" to "java-library",
        "org.gradle.api.plugins.ApplicationPlugin" to "application",
        "org.gradle.api.plugins.GroovyPlugin" to "groovy",
        "org.gradle.api.plugins.ScalaPlugin" to "scala",
        "org.gradle.api.plugins.WarPlugin" to "war",
        "org.gradle.api.plugins.EarPlugin" to "ear",
        "org.gradle.api.plugins.BasePlugin" to "base",
        "org.gradle.api.plugins.JavaBasePlugin" to "org.gradle.java-base",
        "org.gradle.api.plugins.HelpTasksPlugin" to "org.gradle.help-tasks",
        "org.gradle.api.plugins.JvmEcosystemPlugin" to "org.gradle.jvm-ecosystem",
        "org.gradle.api.plugins.JvmTestSuitePlugin" to "org.gradle.jvm-test-suite",
        "org.gradle.api.plugins.JvmToolchainsPlugin" to "org.gradle.jvm-toolchains",
        "org.gradle.api.plugins.ReportingBasePlugin" to "org.gradle.reporting-base",
        "org.gradle.api.plugins.SoftwareReportingTasksPlugin" to "org.gradle.software-reporting-tasks",
        "org.gradle.api.plugins.MavenPublishPlugin" to "maven-publish",
        "org.gradle.api.publish.ivy.plugins.IvyPublishPlugin" to "ivy-publish",
        "org.gradle.language.base.plugins.LifecycleBasePlugin" to "org.gradle.lifecycle-base",
        "org.gradle.testing.base.plugins.TestSuiteBasePlugin" to "org.gradle.test-suite-base",
        "org.gradle.buildinit.plugins.BuildInitPlugin" to "org.gradle.build-init",
        "org.gradle.buildinit.plugins.WrapperPlugin" to "org.gradle.wrapper",
        "org.gradle.kotlin.dsl.provider.plugins.KotlinScriptBasePlugin" to "org.gradle.kotlin.kotlin-dsl-base",
        "org.gradle.api.plugins.JavaPlatformPlugin" to "java-platform",
        "org.gradle.plugins.signing.SigningPlugin" to "signing",
        // Spring
        "org.springframework.boot.gradle.plugin.SpringBootPlugin" to "org.springframework.boot",
        "io.spring.gradle.dependencymanagement.DependencyManagementPlugin" to "io.spring.dependency-management",
        // Kotlin
        "org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapper" to "org.jetbrains.kotlin.jvm",
        "org.jetbrains.kotlin.gradle.plugin.KotlinAndroidPluginWrapper" to "org.jetbrains.kotlin.android",
        "org.jetbrains.kotlin.allopen.gradle.SpringGradleSubplugin" to "org.jetbrains.kotlin.plugin.spring",
        // Android
        "com.android.build.gradle.AppPlugin" to "com.android.application",
        "com.android.build.gradle.LibraryPlugin" to "com.android.library",
        "com.android.build.gradle.DynamicFeaturePlugin" to "com.android.dynamic-feature",
        "dagger.hilt.android.plugin.HiltGradlePlugin" to "com.google.dagger.hilt.android",
        "com.google.devtools.ksp.gradle.KspGradleSubplugin" to "com.google.devtools.ksp",
        "org.jetbrains.kotlin.gradle.internal.Kapt3GradleSubplugin" to "org.jetbrains.kotlin.kapt",
        // Compose
        "org.jetbrains.kotlin.compose.ComposeCompilerGradleSubplugin" to "org.jetbrains.kotlin.plugin.compose",
        "org.jetbrains.compose.ComposePlugin" to "org.jetbrains.compose",
        // KMP
        "org.jetbrains.kotlin.gradle.plugin.KotlinMultiplatformPluginWrapper" to "org.jetbrains.kotlin.multiplatform",
    )

    // ── Framework Detection ──

    private val FRAMEWORK_MAP = mapOf(
        // Android
        "com.android.application" to "Android Application",
        "com.android.library" to "Android Library",
        "com.android.dynamic-feature" to "Android Dynamic Feature",
        "com.google.dagger.hilt.android" to "Hilt (DI)",
        "com.google.devtools.ksp" to "KSP (Kotlin Symbol Processing)",
        "androidx.navigation.safeargs.kotlin" to "Navigation SafeArgs",
        // Kotlin
        "org.jetbrains.kotlin.jvm" to "Kotlin (JVM)",
        "org.jetbrains.kotlin.android" to "Kotlin (Android)",
        "org.jetbrains.kotlin.multiplatform" to "Kotlin Multiplatform (KMP)",
        "org.jetbrains.kotlin.plugin.serialization" to "Kotlin Serialization",
        "org.jetbrains.kotlin.plugin.compose" to "Kotlin Compose Compiler",
        "org.jetbrains.kotlin.kapt" to "KAPT (annotation processing)",
        "org.jetbrains.compose" to "Compose Multiplatform",
        // Server
        "org.springframework.boot" to "Spring Boot",
        "io.ktor" to "Ktor",
        "com.google.protobuf" to "Protobuf/gRPC",
        "org.flywaydb.flyway" to "Flyway",
        "org.liquibase.gradle" to "Liquibase",
        // Quality
        "io.gitlab.arturbosch.detekt" to "Detekt (static analysis)",
    )

    private fun collectPluginsAndFrameworks(proj: org.gradle.api.Project, pluginIds: MutableSet<String>, frameworks: MutableList<String>) {
        val resolved = resolvePluginIds(proj.plugins)
        pluginIds.addAll(resolved)

        for ((pluginId, frameworkName) in FRAMEWORK_MAP) {
            if (pluginId in resolved || proj.plugins.hasPlugin(pluginId)) {
                frameworks.add(frameworkName)
                pluginIds.add(pluginId)
            }
        }
    }

    /** Detect frameworks from dependency coordinates */
    private fun detectFrameworksFromDeps(allDeps: List<String>, frameworks: MutableList<String>) {
        val depPatterns = mapOf(
            // Android / UI
            "androidx.compose.ui:ui" to "Jetpack Compose",
            "androidx.compose.material3" to "Material 3",
            "androidx.compose.material:" to "Material 2 (legacy)",
            "androidx.navigation:navigation-compose" to "Navigation Compose",
            "androidx.navigation:navigation-fragment" to "Navigation (Fragment, legacy)",
            "androidx.hilt:hilt-navigation-compose" to "Hilt Navigation Compose",
            "com.google.dagger:hilt-android" to "Hilt (DI)",
            "com.google.dagger:dagger" to "Dagger (DI, legacy)",
            "io.reactivex.rxjava3:rxjava" to "RxJava 3 (legacy reactive)",
            "io.reactivex.rxjava2:rxjava" to "RxJava 2 (legacy reactive)",
            "io.reactivex.rxjava3:rxandroid" to "RxAndroid (legacy reactive)",
            "io.reactivex.rxjava2:rxandroid" to "RxAndroid (legacy reactive)",
            "androidx.lifecycle:lifecycle-viewmodel-compose" to "ViewModel Compose",
            "androidx.lifecycle:lifecycle-viewmodel-ktx" to "ViewModel KTX",
            "androidx.lifecycle:lifecycle-livedata" to "LiveData (legacy, prefer Flow)",
            "androidx.room:room-runtime" to "Room (local DB)",
            "androidx.room:room-ktx" to "Room KTX",
            "androidx.datastore:datastore" to "DataStore",
            "androidx.work:work-runtime" to "WorkManager",
            "com.squareup.retrofit2:retrofit" to "Retrofit (HTTP)",
            "com.squareup.okhttp3:okhttp" to "OkHttp",
            "com.squareup.moshi:moshi" to "Moshi (JSON)",
            "com.google.code.gson:gson" to "Gson (JSON, legacy)",
            "org.jetbrains.kotlinx:kotlinx-coroutines" to "Kotlin Coroutines",
            "org.jetbrains.kotlinx:kotlinx-serialization" to "Kotlin Serialization",
            "com.jakewharton.timber:timber" to "Timber (logging)",
            "io.coil-kt:coil" to "Coil (image loading)",
            "com.github.bumptech.glide:glide" to "Glide (image loading, legacy)",
            "com.squareup.picasso:picasso" to "Picasso (image loading, legacy)",
            // Kotlin Multiplatform
            "org.jetbrains.kotlinx:kotlinx-coroutines-core" to "Kotlin Coroutines",
            // Server
            "org.flywaydb:flyway" to "Flyway",
            "org.liquibase:liquibase" to "Liquibase",
            "spring-boot-starter-web" to "Spring Web (REST)",
            "spring-boot-starter-data-jpa" to "Spring Data JPA",
            "spring-boot-starter-security" to "Spring Security",
            "spring-boot-starter-webflux" to "Spring WebFlux (Reactive)",
            "spring-boot-starter-data-mongodb" to "Spring Data MongoDB",
            "spring-boot-starter-data-redis" to "Spring Data Redis",
            "testcontainers" to "Testcontainers",
            "io.ktor:ktor-client" to "Ktor Client",
            "io.ktor:ktor-server" to "Ktor Server",
            "io.grpc:grpc" to "gRPC",
            "org.jooq:jooq" to "jOOQ",
            "com.graphql-java" to "GraphQL",
            // DI
            "io.insert-koin:koin" to "Koin (DI)",
            // Kotlin libraries
            "org.jetbrains.kotlinx:kotlinx-io" to "kotlinx-io",
            // Database
            "org.jetbrains.exposed:exposed" to "Exposed (SQL)",
            // Quality / Architecture
            "com.lemonappdev:konsist" to "Konsist (architecture tests)",
        )
        for ((pattern, name) in depPatterns) {
            if (allDeps.any { it.contains(pattern) } && name !in frameworks) {
                frameworks.add(name)
            }
        }
    }

    // ── Source Sets ──

    private fun appendSourceSets(sb: StringBuilder, proj: org.gradle.api.Project, root: org.gradle.api.Project) {
        try {
            val javaExt = proj.extensions.findByType(JavaPluginExtension::class.java) ?: return
            val sourceSets = javaExt.sourceSets
            val label = if (proj == root && root.subprojects.isEmpty()) "Source Sets" else "Source Sets (${proj.path})"
            val entries = mutableListOf<String>()
            sourceSets.forEach { ss ->
                val dirs = ss.allSource.srcDirs.filter { it.exists() }
                if (dirs.isNotEmpty()) {
                    entries.add("- **${ss.name}:** ${dirs.joinToString(", ") { it.relativeTo(root.projectDir).path }}")
                }
            }
            if (entries.isNotEmpty()) {
                sb.appendLine()
                sb.appendLine("## $label")
                sb.appendLine()
                entries.forEach { sb.appendLine(it) }
            }
        } catch (_: Exception) {}
    }

    // ── Dependencies ──

    private fun appendDependencies(sb: StringBuilder, proj: org.gradle.api.Project, errors: MutableList<String>, allDeps: MutableList<String>) {
        val interestingConfigs = setOf("implementation", "api", "compileOnly", "runtimeOnly",
            "testImplementation", "testCompileOnly", "testRuntimeOnly")
        val label = if (proj == proj.rootProject && proj.rootProject.subprojects.isEmpty()) "Dependencies" else "Dependencies (${proj.path})"
        val entries = mutableListOf<String>()

        // Try to get resolved versions
        val resolvedVersions = mutableMapOf<String, String>() // "group:name" → version
        for (configName in listOf("compileClasspath", "runtimeClasspath", "testCompileClasspath")) {
            val config = try { proj.configurations.findByName(configName) } catch (_: Exception) { null }
            if (config == null || !config.isCanBeResolved) continue
            try {
                config.resolvedConfiguration.firstLevelModuleDependencies.forEach { dep ->
                    resolvedVersions["${dep.moduleGroup}:${dep.moduleName}"] = dep.moduleVersion
                    // Also capture transitive first-level for version lookup
                    dep.children.forEach { child ->
                        resolvedVersions["${child.moduleGroup}:${child.moduleName}"] = child.moduleVersion
                    }
                }
            } catch (e: Exception) {
                errors.add("Failed to resolve `$configName` in ${proj.path}: ${e.message?.take(120)}")
            }
        }

        for (configName in interestingConfigs) {
            val config = try { proj.configurations.findByName(configName) } catch (_: Exception) { null }
            if (config == null) continue
            val deps = config.dependencies.filter { it !is ProjectDependency }
            if (deps.isEmpty()) continue
            for (dep in deps) {
                val group = dep.group ?: ""
                val name = dep.name
                val declaredVersion = dep.version ?: ""
                val resolvedVersion = resolvedVersions["$group:$name"] ?: declaredVersion
                val coord = "$group:$name:$resolvedVersion"
                entries.add("- `$configName`: $coord")
                allDeps.add(coord)
            }
        }

        if (entries.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## $label")
            sb.appendLine()
            entries.forEach { sb.appendLine(it) }
        }
    }

    // ── Architecture Hints ──

    private fun generateHints(frameworks: List<String>): List<String> {
        val hints = mutableListOf<String>()
        val isAndroid = frameworks.any { it.startsWith("Android") }
        val hasCompose = "Jetpack Compose" in frameworks || "Compose Multiplatform" in frameworks
        val hasRxJava = frameworks.any { it.contains("RxJava") || it.contains("RxAndroid") }
        val hasCoroutines = "Kotlin Coroutines" in frameworks
        val hasHilt = frameworks.any { it.contains("Hilt") }
        val hasDagger = "Dagger (DI, legacy)" in frameworks && !hasHilt
        val hasNavCompose = "Navigation Compose" in frameworks
        val hasNavFragment = "Navigation (Fragment, legacy)" in frameworks
        val hasLiveData = "LiveData (legacy, prefer Flow)" in frameworks
        val hasRoom = frameworks.any { it.contains("Room") }
        val hasKMP = "Kotlin Multiplatform (KMP)" in frameworks

        // ── Android ──
        if (isAndroid) {
            if (hasCompose && hasRxJava) {
                hints.add("⚡ MIGRATION IN PROGRESS: Legacy Android (RxJava, XML) → Modern (Compose, Coroutines)")
                hints.add("Legacy code uses RxJava + XML layouts. New code should use Compose + Coroutines/Flow")
                hints.add("Migration strategy: new screens in Compose, refactor existing screens incrementally")
            } else if (hasCompose) {
                hints.add("Jetpack Compose UI → @Composable functions, unidirectional data flow, State hoisting")
            } else {
                hints.add("Legacy Android UI → XML layouts, Activities/Fragments, View Binding or DataBinding")
            }

            if (hasRxJava && hasCoroutines) {
                hints.add("RxJava + Coroutines coexist → migrate RxJava chains to Flow/suspend functions incrementally")
                hints.add("Use kotlinx-coroutines-rx3 bridge for interop during migration")
            } else if (hasRxJava) {
                hints.add("RxJava present → Observable/Single/Completable patterns. Migration target: Kotlin Flow + suspend")
            }

            if (hasHilt) {
                hints.add("Hilt DI → @HiltAndroidApp, @AndroidEntryPoint, @Inject, @HiltViewModel")
            } else if (hasDagger) {
                hints.add("Dagger (legacy) → consider migrating to Hilt for simpler Android DI")
            }

            if (hasNavCompose) {
                hints.add("Navigation Compose → NavHost, composable() routes, type-safe navigation")
            } else if (hasNavFragment) {
                hints.add("Navigation Fragment (legacy) → nav_graph.xml, Fragment destinations. Migration target: Navigation Compose")
            }

            if (hasLiveData && hasCoroutines) {
                hints.add("LiveData present → migrate to StateFlow/SharedFlow for new ViewModels")
            } else if (hasLiveData) {
                hints.add("LiveData present → migration target: Kotlin StateFlow + Coroutines")
            }

            if (hasRoom) {
                hints.add("Room DB → @Entity, @Dao, @Database. Migrations via Migration class or auto-migration")
            }

            if ("Glide (image loading, legacy)" in frameworks || "Picasso (image loading, legacy)" in frameworks) {
                val legacy = if ("Glide (image loading, legacy)" in frameworks) "Glide" else "Picasso"
                hints.add("$legacy present → migration target: Coil (Compose-native image loading)")
            }

            if ("Gson (JSON, legacy)" in frameworks) {
                hints.add("Gson present → migration target: Kotlin Serialization or Moshi")
            }

            // Android source conventions
            hints.add("Android source layout: src/main/java (or kotlin), src/main/res (layouts, drawables, values)")
        }

        // ── Kotlin Multiplatform ──
        if (hasKMP) {
            hints.add("Kotlin Multiplatform → shared code in commonMain, platform-specific in androidMain/iosMain etc.")
            hints.add("KMP: expect/actual declarations for platform-specific implementations")
            if ("Ktor Client" in frameworks) {
                hints.add("Ktor Client in KMP → shared HTTP layer across platforms")
            }
            if ("Kotlin Serialization" in frameworks) {
                hints.add("KMP + Kotlin Serialization → shared data models across platforms")
            }
        }

        // ── Compose Multiplatform ──
        if ("Compose Multiplatform" in frameworks) {
            hints.add("Compose Multiplatform → shared UI in commonMain, platform-specific in androidMain/desktopMain/iosMain")
        }

        // ── Ktor ──
        if ("Ktor Server" in frameworks) {
            hints.add("Ktor Server → routing DSL, application modules, install() for features")
        }
        if ("Ktor Client" in frameworks && !hasKMP) {
            hints.add("Ktor Client → HTTP client, can replace Retrofit")
        }

        // ── Spring ──
        if ("Spring Boot" in frameworks) {
            hints.add("Spring Boot → controller/service/repository pattern")
        }
        if ("Spring Web (REST)" in frameworks) {
            hints.add("Spring Web → REST controllers with @RequestMapping/@GetMapping")
        }
        if ("Spring Data JPA" in frameworks) {
            hints.add("Spring Data JPA → @Entity classes, Spring Data repositories")
        }
        if ("Spring Security" in frameworks) {
            hints.add("Spring Security → new endpoints may need auth rules, check SecurityConfig")
        }
        if ("Spring WebFlux (Reactive)" in frameworks) {
            hints.add("Spring WebFlux → reactive, use Mono/Flux not blocking calls")
        }
        if ("Flyway" in frameworks || "Liquibase" in frameworks) {
            hints.add("Database migrations → schema changes REQUIRE migration files")
        }
        if ("Spring Data JPA" in frameworks && ("Flyway" in frameworks || "Liquibase" in frameworks)) {
            hints.add("JPA + migrations → entity changes need: 1) migration 2) entity update 3) test")
        }

        // ── General ──
        if ("Protobuf/gRPC" in frameworks || "gRPC" in frameworks) {
            hints.add("Protobuf/gRPC → .proto files generate code, never edit generated sources")
        }
        if ("Kotlin Serialization" in frameworks && !hasKMP) {
            hints.add("Kotlin Serialization → @Serializable data classes, not Jackson/Gson")
        }
        if ("Testcontainers" in frameworks) {
            hints.add("Testcontainers → integration tests need Docker running")
        }
        if ("jOOQ" in frameworks) {
            hints.add("jOOQ → type-safe SQL from generated code, regenerate after schema changes")
        }
        if ("GraphQL" in frameworks) {
            hints.add("GraphQL → check for .graphql schema files")
        }

        return hints
    }
}
