package zone.clanker.gradle

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import zone.clanker.gradle.generators.InstructionsGenerator
import zone.clanker.gradle.generators.ToolAdapterRegistry
import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class InstructionsGeneratorTest {

    @TempDir
    lateinit var buildDir: File

    @TempDir
    lateinit var projectDir: File

    @Test
    fun `claude generates to dot-claude CLAUDE md`() {
        val files = InstructionsGenerator.generate(buildDir, listOf("claude"))
        assertEquals(1, files.size)
        assertEquals(".claude/CLAUDE.md", files[0].relativePath)
        assertFalse(files[0].file.readText().contains("OPSX:BEGIN")) // not append mode
    }

    @Test
    fun `copilot generates path-specific instructions file`() {
        val files = InstructionsGenerator.generate(buildDir, listOf("github-copilot"))
        assertEquals(1, files.size)
        assertEquals(".github/instructions/opsx.instructions.md", files[0].relativePath)
    }

    @Test
    fun `codex generates to root AGENTS md with markers`() {
        val files = InstructionsGenerator.generate(buildDir, listOf("codex"))
        assertEquals(1, files.size)
        assertEquals("AGENTS.md", files[0].relativePath)
        assertTrue(files[0].file.readText().contains("OPSX:BEGIN"))
        assertTrue(files[0].file.readText().contains("OPSX:END"))
    }

    @Test
    fun `opencode generates to root AGENTS md with markers`() {
        val files = InstructionsGenerator.generate(buildDir, listOf("opencode"))
        assertEquals(1, files.size)
        assertEquals("AGENTS.md", files[0].relativePath)
        assertTrue(files[0].file.readText().contains("OPSX:BEGIN"))
    }

    @Test
    fun `crush generates to root AGENTS md with markers`() {
        val files = InstructionsGenerator.generate(buildDir, listOf("crush"))
        assertEquals(1, files.size)
        assertEquals("AGENTS.md", files[0].relativePath)
    }

    @Test
    fun `deduplicates AGENTS md when multiple agents share it`() {
        val files = InstructionsGenerator.generate(buildDir, listOf("codex", "opencode", "crush"))
        assertEquals(1, files.size) // not 3!
        assertEquals("AGENTS.md", files[0].relativePath)
    }

    @Test
    fun `generates separate files for non-overlapping agents`() {
        val files = InstructionsGenerator.generate(buildDir, listOf("claude", "github-copilot", "codex"))
        assertEquals(3, files.size) // claude + copilot + AGENTS.md
    }

    @Test
    fun `instruction content includes task catalog`() {
        val files = InstructionsGenerator.generate(buildDir, listOf("claude"))
        val content = files[0].file.readText()
        assertTrue(content.contains("opsx-context"))
        assertTrue(content.contains("opsx-tree"))
        assertTrue(content.contains("opsx-find"))
        assertTrue(content.contains("opsx-arch"))
        assertTrue(content.contains("opsx-rename"))
    }

    @Test
    fun `instruction content forbids scripts`() {
        val files = InstructionsGenerator.generate(buildDir, listOf("claude"))
        val content = files[0].file.readText()
        assertTrue(content.contains("NEVER create Python"))
        assertTrue(content.contains("Bash"))
    }

    @Test
    fun `install appends to existing AGENTS md preserving user content`() {
        val userContent = "# My Project\n\nCustom rules here.\n"
        val agentsFile = File(projectDir, "AGENTS.md")
        agentsFile.writeText(userContent)

        val files = InstructionsGenerator.generate(buildDir, listOf("codex"))
        val adapter = ToolAdapterRegistry.get("codex")!!
        InstructionsGenerator.install(files[0], projectDir, adapter)

        val result = agentsFile.readText()
        assertTrue(result.contains("My Project")) // user content preserved
        assertTrue(result.contains("OPSX")) // our content added
        assertTrue(result.contains("OPSX:BEGIN"))
        assertTrue(result.contains("OPSX:END"))
    }

    @Test
    fun `install replaces existing OPSX section on re-sync`() {
        val existingContent = "# My Project\n\n<!-- OPSX:BEGIN - Generated by openspec-gradle. Do not edit between markers. -->\nold content\n<!-- OPSX:END -->\n\n# Footer\n"
        val agentsFile = File(projectDir, "AGENTS.md")
        agentsFile.writeText(existingContent)

        val files = InstructionsGenerator.generate(buildDir, listOf("codex"))
        val adapter = ToolAdapterRegistry.get("codex")!!
        InstructionsGenerator.install(files[0], projectDir, adapter)

        val result = agentsFile.readText()
        assertTrue(result.contains("My Project"))
        assertTrue(result.contains("Footer"))
        assertFalse(result.contains("old content"))
        assertTrue(result.contains("OPSX"))
    }

    @Test
    fun `clean removes OPSX section but preserves user content`() {
        val content = "# My Rules\n\n<!-- OPSX:BEGIN - Generated by openspec-gradle. Do not edit between markers. -->\n\nOPSX stuff\n<!-- OPSX:END -->\n"
        val agentsFile = File(projectDir, "AGENTS.md")
        agentsFile.writeText(content)

        val adapter = ToolAdapterRegistry.get("codex")!!
        InstructionsGenerator.clean(projectDir, adapter)

        val result = agentsFile.readText()
        assertTrue(result.contains("My Rules"))
        assertFalse(result.contains("OPSX stuff"))
        assertFalse(result.contains("OPSX:BEGIN"))
    }

    @Test
    fun `clean deletes file if only OPSX content existed`() {
        val content = "<!-- OPSX:BEGIN - Generated by openspec-gradle. Do not edit between markers. -->\n\nOPSX stuff\n<!-- OPSX:END -->\n"
        val agentsFile = File(projectDir, "AGENTS.md")
        agentsFile.writeText(content)

        val adapter = ToolAdapterRegistry.get("codex")!!
        InstructionsGenerator.clean(projectDir, adapter)

        assertFalse(agentsFile.exists())
    }
}
